### ISSUE TITLE
Hi, where is "mcts/mcts.h" ?

### ISSUE THREAD

**Issue by mengxingshifen1218** [bark-simulator/planner-mcts#10]

**Comment by patrickhart** [comment]
This is due to the bazel system that automatically pulls dependencies specified, e.g., have a look here: https://github.com/bark-simulator/planner-mcts/blob/e3181ef33c8d4c6fe1c89c89437b39c8e1abeb70/src/BUILD

Furthermore, you can find the external dependencies defined here: https://github.com/bark-simulator/planner-mcts/blob/master/util/deps.bzl

To conclude, you can find them here: https://github.com/juloberno/mamcts
